PAUSE

#CREACION DE DISCOS_____________________________________________________

mkdisk -size=100 -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk"
mkdisk -size=100 -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk"
mkdisk -size=100 -path="/home/angel/Descargas/otros/mis discos/Disco3.dsk"
mkdisk -size=100 -path="/home/angel/Descargas/otros/mis discos/Disco4.dsk"

#rmdisk -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" 


fdisk -size=50 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=PartX      -type=L #NO SE PUEDE AGREGAR LOGICA NO "E"
fdisk -size=10 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion1
fdisk -size=10 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion1         #NOMBRE REPETIDO
fdisk -size=20 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion2 -type=e
fdisk -size=90 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=PartX              #FALTA DE ESPACIO EN EL DICO
fdisk -size=30 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion3
fdisk -size=50 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=PartX      -type=e #YA HAY UNA "EXTENDIDA"
fdisk -size=10 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion4         #QUEDAN 30 MG LIBRES
fdisk -size=50 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=PartX              #NO SE PUEDE AGREGAR PORQUE YA HAY 4



fdisk -size=5 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL1 -type=l
fdisk -size=5 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL2 -type=l
fdisk -size=5 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL3 -type=l
fdisk -size=5 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL4 -type=l
fdisk -size=5 -unit=m -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL5 -type=l #FALTA DE ESPACIO EN LA EXTENDIDA


fdisk -size=1 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par1
fdisk -size=1 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par2
fdisk -size=1 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par3
fdisk -size=1 -unit=M -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par4







mount -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion1 #id=581A
mount -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL1      #id=581B
mount -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=ParL1      #ERROR YA MONTADA
mount -path="/home/angel/Descargas/otros/mis discos/Disco1.dsk" -name=Particion4 #id=581C


mount -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par1 #id=582A
mount -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par2 #id=582B
mount -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par3 #id=582C
mount -path="/home/angel/Descargas/otros/mis discos/Disco2.dsk" -name=Par4 #id=582D



rep -path="/home/angel/Descargas/otros/misdiscos/Disco1.jpg" -name=disk -id=581A
rep -path="/home/angel/Descargas/otros/misdiscos/Disco2.jpg" -name=disk -id=582A


#Parte 2

mkfs -type=full -id=581A
mkfs -type=full -id=582A


Login -password=123 -usuario=root -id=581A

#para la particion 581A
#CREACION DE GRUPOS
mkgrp -naMe=581AGrupo1
mkgrp -NamE=581AGrupo2
mkgrp -name="581A Grupo3"
mkgrp -NamE=581AGrupo2 #repetido

#AGREGAR USUARIOS
Mkusr -usuario="user1" -grp=root -pwd=123
Mkusr -usuario="user2" -grp=581AGrupo1 -pwd=456
Mkusr -usuario="user3" -grp=581AGrupo2 -pwd=789
Mkusr -usuario="user3" -grp=581AGrupo2 -pwd=789 #repetido

#Eliminar Grupos
rmgrp -name=581AGrupo2

logout



Login -password=123 -usuario=root -id=582A

#para la particion 582A
#CREACION DE GRUPOS
mkgrp -naMe=582Azz1
mkgrp -NamE=582Azz2
mkgrp -name="582A zz3"

#AGREGAR USUARIOS
Mkusr -usuario="userz1" -grp=root -pwd=z123
Mkusr -usuario="userz2" -grp=582Azz1 -pwd=z456
Mkusr -usuario="userz3" -grp=582Azz2 -pwd=z789

#Eliminar Grupos
rmgrp -name=582Azz1

logout

Login -password=z789 -usuario=userz3 -id=582A
#CREACION DE GRUPOS
mkgrp -naMe=582Azz1 #ERROR NO ROOT

logout
Login -password=123 -usuario=root -id=582A

mkfile -size=15 -path=/home/user/docs/noExiste/a.txt -r
mkfile -size=15 -path=/hdaome/alameda/dedos/b.txt #error no permisos

mkdir -p -path=/home/user/docs/usac
mkdir -path=/home/dedos/carlos/usac #error no hay permisos

mkfile -path=/home/user/docs/b.txt -r -cont=/home/angel/Descargas/copiar.txt


rep -id=582A -Path="/home/parte2/reportes/users_3.txt" -ruta="/user.txt" -name=file
rep -id=582A -Path="/home/parte2/reportes/copia.txt" -ruta="/home/user/docs/b.txt" -name=file




